In [1]:
a=[[11,12,13],[21,22,23],[31,32,33]]

In [2]:
import numpy as np

In [3]:
A=np.array(a)

In [4]:
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [5]:
A.ndim

2

In [6]:
A.shape

(3, 3)

In [7]:
A.shape

(3, 3)

In [9]:
A.size

9

In [10]:
A[1][1]

22

In [11]:
A[2][0]

31

In [12]:
A[1,1]

22

In [13]:
A[2,2]

33

In [14]:
A[1,0:3]

array([21, 22, 23])

In [15]:
x=np.array([[111,999],[444,666],[888,222]])
y=np.array([[999,111],[888,222],[111,777]])

In [16]:
z=x+y

In [17]:
z

array([[1110, 1110],
       [1332,  888],
       [ 999,  999]])

In [18]:
l=2*x*y

In [19]:
l

array([[221778, 221778],
       [788544, 295704],
       [197136, 344988]])

In [24]:
o=np.array([[999,111,444],[333,555,777],[222,888,555]])
i=np.array([[222,333,111],[555,999,777],[666,888,111]])

In [25]:
k=np.dot(i,o)

In [26]:
k

array([[ 357309,  308025,  418914],
       [1059606, 1306026, 1453878],
       [ 985680,  665334, 1047285]])

In [29]:
p=np.array([[1,0],[0,1]])
q=np.array([[2,1],[1,2]]) 
r=np.dot(X,Y)

In [30]:
r

array([[2, 1],
       [1, 2]])